[versions]
agp = "8.8.0"
kotlin = "2.0.0"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2023.08.00"
lifecycleViewmodelCompose = "2.7.0"
serialization = "1.8.10"
coilCompose = "2.4.0"
retrofit = "2.9.0"
retrofit2KotlinxSerializationConverterVersion = "1.0.0"
kotlinxSerializationJson = "1.5.1"
converterGson = "2.9.0"
navigationCompose = "2.7.7"
okhttp = "4.11.0"
coilSVG = "2.6.0"
playServicesAds = "23.2.0"
datastorePreferences = "1.1.1"

#Dagger-Hilt
#hilt = "2.49"
#hiltCompiler = "1.2.0"
hiltNavigationCompose = "1.2.0"
kapt = "2.0.21"
hilt = "2.56.2"

#Room
roomDatabase = "2.7.1"

#KSP
ksp = "2.0.21-1.0.28"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose"}

#Retrofit/Okhttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
jakewharton-retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverterVersion"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose"}
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coilSVG"}

#Google Play Services Ads
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds"}

#Android Datastore Preferences
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

#Dagger-Hilt
#dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
#dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt"}
#hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompiler"}
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose"}

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}

#Room Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomDatabase"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomDatabase"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomDatabase"}
room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "roomDatabase"}
room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "roomDatabase"}
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomDatabase"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
jetbrainsSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

